"""change field

Revision ID: 5d6cb4737bd3
Revises: cce415eedc76
Create Date: 2026-02-25 21:41:42.888917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5d6cb4737bd3"
down_revision: Union[str, Sequence[str], None] = "cce415eedc76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blogs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("slug", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("content", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("excerpt", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("image_url", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("is_published", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("published_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.create_index(batch_op.f("ix_blogs_slug"), ["slug"], unique=True)
        batch_op.drop_column("description")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blogs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f("ix_blogs_slug"))
        batch_op.drop_column("published_at")
        batch_op.drop_column("is_published")
        batch_op.drop_column("image_url")
        batch_op.drop_column("excerpt")
        batch_op.drop_column("content")
        batch_op.drop_column("slug")

    # ### end Alembic commands ###
